# Generated by Django 6.0.6 on 2026-07-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='staus',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
