# Generated by Django 6.0.6 on 2026-07-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('archetype', models.CharField(max_length=50)),
                ('traits', models.JSONField(default=list)),
                ('philosophy', models.TextField(blank=True)),
            ],
        ),
    ]
