# Generated by Django 6.0.6 on 2026-07-11 08:09

import apps.dossiers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='avatarUrl',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
