# Generated by Django 6.0.6 on 2026-07-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_dossier_avatarurl_dossier_birthdate_dossier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='avatarUrl',
            new_name='avatar_url',
        ),
    ]
