# Generated by Django 6.0.6 on 2026-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_rename_avatarurl_dossier_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='maxDistance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='phone',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
