# Generated by Django 6.0.6 on 2026-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_discoveryexposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='archetype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
