# Generated by Django 6.0.6 on 2026-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_alter_dossier_archetype_alter_dossier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='philosophy',
            new_name='lifestyle',
        ),
        migrations.AddField(
            model_name='dossier',
            name='value_system',
            field=models.TextField(blank=True),
        ),
    ]
