# Generated by Django 6.0.6 on 2026-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_rename_philosophy_dossier_lifestyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='philosophy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
